### ISSUE TITLE
PHP Version Error

### ISSUE THREAD

**Issue by alep93** [swissup/module-upward-connector#1]
Hi, I tried to use this module to configure my PWA Storefront, but i receive the error with php required version. I use php@8.2.
It possibile to remove from composer.json php requirements?
Thanks

**Comment by 0m3r** [comment]
Yes, It's possible. That requirement was inherited from magento/magento2-upward-connector.

https://github.com/magento/magento2-upward-connector/blob/develop/composer.json#L8
https://github.com/magento/magento2-upward-connector/commit/7d21e535295218a3d75efe7b1b82a2e47a03641d

![Знімок екрана з 2024-01-30 12-19-22](https://github.com/swissup/module-upward-connector/assets/412612/3bdfb389-301a-4057-b6c9-2fc1a6f94d73)
